### ISSUE TITLE
Expression metrics are not imported to Superset

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#153]
### Description
Users are able to specify metrics on the `schema.yml` file, that should be created on Superset as dataset metrics. However, if the metric is an `expression`, since they don't have a `model` key, they don't get associated to any dataset on Superset.

### How to reproduce the issue
1. Create expression metrics on your `schema.yml` file. For example:
```
metrics:
  - name: total_revenue
    label: SUM of all price_each
    model: ref('modeled_sales')
    description: "The SUM of all price_each"
    type: sum
    sql: price_each
    timestamp: date
    time_grains: [day, week, month, year]
  - name: revenue_multiplied
    label: "Revenue calculated differently"
    description: "Let's try to use an expression"
    type: expression
    sql: "{{metric('total_revenue')}} * 1.25"
    timestamp: date
    time_grains: [day, week, month, year]
```
2. Sync data to Superset.

### Expected Results
Both `total_revenue` and `revenue_multiplied` should be created on the `modeled_sales` dataset in Superset.

### Actual Results
Only `total_revenue` is created on the `modeled_sales` dataset in Superset.
