### ISSUE TITLE
Derived metrics are not created properly on Superset

### ISSUE THREAD

**Issue by Vitor-Avila** [preset-io/backend-sdk#158]
Derived metrics are not properly created on Superset. For example, below schema:
```
metrics:
  - name: countries_count
    label: "Count of unique countries"
    model: ref('modeled_sales')
    description: "Count distinct countries"
    calculation_method: count_distinct
    expression: country
    timestamp: date
    time_grains: [day, week, month, year]
  - name: total_revenue
    label: SUM of all price_each
    model: ref('modeled_sales')
    description: "The SUM of all price_each"
    calculation_method: sum
    expression: price_each
    timestamp: date
    time_grains: [day, week, month, year]
  - name: avg_sum_per_country
    label: "AVG revenue per country"
    description: "Let's try to two expressions"
    calculation_method: derived
    expression: "{{metric('total_revenue')}} / {{metric('countries_count')}}"
    timestamp: date
    time_grains: [day, week, month, year]
```

Would create 3 metrics on Superset, however the nested SQL syntax wouldn't be added. Instead, the metric name is used:
<img width="876" alt="image" src="https://user-images.githubusercontent.com/96086495/205666677-0dca914f-d00f-4d9d-94d1-6c5a2fa9fecf.png">

Superset can't handle the metrics by their name, since they are not actual columns on the dataset. Using those metrics on a chart results in an error similar to this:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/96086495/205666942-bc58c667-0a1e-4377-89f8-3046b056d8e1.png">
