### ISSUE TITLE
synced dbt exposures name need to be an identifier

### ISSUE THREAD

**Issue by advincze-hivemq** [preset-io/backend-sdk#207]
rev: `8c7a4b81bd4e1f94aaeb504b278fe7a12ff7e820`

currently the synced exposures from  are added in the following way:
```
version: 2
exposures:
- name: <chart name>
  type: analysis
  maturity: low
  url: <chart url>
  description: ''
  depends_on:
  - ref('...')
  owner:
    name: Bob
    email: unknown
...
```

however the exposure name needs to be an identifier (see https://docs.getdbt.com/docs/build/exposures#declaring-an-exposure)
in snake case so that it can be also used from the dbt docs lineage

the id could be used as a `name` instead and the chart name can be added as the `label` field
