### ISSUE TITLE
Exposure option YML data

### ISSUE THREAD

**Issue by dweaver33** [preset-io/backend-sdk#43]
When using the `exposures` option, some of the data is missing or lacks a way to control content.  

As you can see in the example file below, I have the following issues:
1. Email is missing
2. Unable to change the following fields:
  - Type
  - Maturity
  - Description

Example exposure file:
```yml
version: 2
exposures:
- name: Number of Customers per Day [chart]
  type: analysis
  maturity: low
  url: https://*********.app.preset.io/superset/explore/?form_data=********
  description: ''
  depends_on:
  - ref('ref_contacts')
  owner:
    name: Dustin Weaver
    email: unknown
- name: Customer Dashboard [dashboard]
  type: dashboard
  maturity: low
  url: https://**********.app.preset.io/superset/dashboard/9/
  description: ''
  depends_on:
  - ref('ref_contacts')
  owner:
    name: Dustin Weaver
    email: unknown
```

**Comment by betodealmeida** [comment]
Hi, Dustin!

How do you see this working? Adding the email is doable but not straightforward, since requires changing the existing APIs in Superset to return the information, or doing additional API calls. But I'm not sure how to change type/maturity/description.

Right now charts are mapped to `analysis`, and dashboards to `dashboard`. If a dashboard is published the maturity is exported as high; same if a chart is certified. if we want to allow the user to override that behavior the only way I can see is by having them add metadata to the "extra" field, something like:

```yaml
dbt:
    type: XXX
    description: YYY
    maturity: high
```

We could also do that for email as a workaround.

For `description` we could potentially add the field to dashboards and charts, and use that, but it would require some design work.
